version: '3.8'
services:
  app:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend:/app
    restart: unless-stopped
    environment:
      - NODE_ENV=production