# Use official Node image
FROM node:18-slim

# Install ffmpeg and libreoffice (for conversions)
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg libreoffice \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package.json ./
RUN npm install --production
COPY . .

# create upload dir
RUN mkdir -p uploads

EXPOSE 5000
CMD ["node", "server.js"]